Inside the **try{} statement**, you can write the code having errors or possibilities of the errors. You can add regular JavaScript code into the try{} statement.

The **catch{} statement** is used to handle the errors.

## Syntax
![[Pasted image 20250305151407.png]]

## Example

![[Pasted image 20250305151743.png]]

![[Pasted image 20250305151931.png]]

## JavaScript try…catch…finally Statement
The finally{} statement allows you to execute the particular code after completing the execution of the try{} and catch{} statements.

![[Pasted image 20250305152113.png]]

![[Pasted image 20250305152148.png]]

## JavaScript Throw Statement
### Throwing the Error object
![[Pasted image 20250305152839.png]]

### Throwing the primitive value
![[Pasted image 20250305152932.png]]

### Input Validation Example
![[Pasted image 20250305153125.png]]

## Nesting Try Blocks

![[Pasted image 20250305153235.png]]

![[Pasted image 20250305153338.png]]
![[Pasted image 20250305153445.png]]

## JavaScript try...catch with setTimeout() Method

![[Pasted image 20250305153557.png]]

## Promise-based Errors

![[Pasted image 20250305153703.png]]








